import { getOctokit } from '@actions/github';
import type { EngineResult } from '../engine';
import type { DiffModel } from '../diff/parse';

const MARKER = '<!-- agentgate -->';

function buildBody(result: EngineResult, diff: DiffModel): string {
  const { verdict, findings } = result;

  const header =
    verdict === 'pass'
      ? '## ✅ AgentGate: Passed'
      : verdict === 'warn'
        ? '## ⚠️ AgentGate: Warnings'
        : '## ❌ AgentGate: Blocked';

  const lines: string[] = [
    MARKER,
    header,
    '',
    `**${diff.files.length}** files changed &nbsp;·&nbsp; **+${diff.totalAdded} -${diff.totalDeleted}** lines`,
    '',
  ];

  if (findings.length === 0) {
    lines.push('No issues found.');
  } else {
    lines.push('| Rule | Findings | Severity |');
    lines.push('|------|----------|----------|');

    const byRule = new Map<string, { count: number; severity: string }>();
    for (const f of findings) {
      const entry = byRule.get(f.ruleId) ?? { count: 0, severity: f.severity };
      entry.count++;
      byRule.set(f.ruleId, entry);
    }

    for (const [rule, { count, severity }] of byRule) {
      const icon = severity === 'error' ? '❌' : severity === 'warning' ? '⚠️' : 'ℹ️';
      lines.push(`| \`${rule}\` | ${count} | ${icon} ${severity} |`);
    }

    lines.push('');
    lines.push('<details><summary>View findings</summary>');
    lines.push('');

    for (const [ruleId] of byRule) {
      lines.push(`**${ruleId}**`);
      for (const f of findings.filter((x) => x.ruleId === ruleId)) {
        const loc = f.file ? (f.line ? `\`${f.file}:${f.line}\`` : `\`${f.file}\``) : '';
        lines.push(`- ${loc ? `${loc} — ` : ''}${f.message}`);
        if (f.suggestion) lines.push(`  > 💡 ${f.suggestion}`);
      }
      lines.push('');
    }

    lines.push('</details>');
  }

  lines.push('');
  lines.push(
    '<sub>Generated by [AgentGate](https://github.com/brett-buskirk/agent-gate)</sub>',
  );

  return lines.join('\n');
}

export async function upsertComment(
  token: string,
  owner: string,
  repo: string,
  pullNumber: number,
  result: EngineResult,
  diff: DiffModel,
): Promise<void> {
  const octokit = getOctokit(token);
  const body = buildBody(result, diff);

  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: pullNumber,
    per_page: 100,
  });

  const existing = comments.find((c) => c.body?.includes(MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
  } else {
    await octokit.rest.issues.createComment({ owner, repo, issue_number: pullNumber, body });
  }
}
